server:
  port: 8090
spring:
  application:
    name: shiro-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc://mysql://localhost:3306/test
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:*/*.xml
logging:
  level:
    root: info
    pers.will.shirodemo.mapper: debug